apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-pressure
  namespace: slab-stress-test
  labels:
    app: memory-pressure
spec:
  # Multiple replicas to collectively exhaust node memory.
  # Each pod allocates ALLOC_MB of anonymous memory.
  # Total pressure = replicas * ALLOC_MB.
  replicas: 6
  selector:
    matchLabels:
      app: memory-pressure
  template:
    metadata:
      labels:
        app: memory-pressure
    spec:
      terminationGracePeriodSeconds: 0
      volumes:
      - name: mem-vol
        emptyDir:
          # memory-backed tmpfs: writes here create anonymous pages
          # that count against the pod's cgroup and node memory
          medium: Memory
      containers:
      - name: pressure
        image: memory-pressure:local
        imagePullPolicy: Never
        volumeMounts:
        - name: mem-vol
          mountPath: /mem
        env:
        - name: ALLOC_MB
          value: "400"
        - name: CHUNK_MB
          value: "32"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "250m"
